apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: microservice_implement_stockmanagement-flask-frontend
  name: microservice_implement_stockmanagement-flask-frontend
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: microservice_implement_stockmanagement-flask-frontend
status:
  loadBalancer: {}