apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: microservice_implement_stockmanagement-sql-server-backend
  name: microservice_implement_stockmanagement-sql-server-backend
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    io.kompose.service: microservice_implement_stockmanagement-sql-server-backend
status:
  loadBalancer: {}