apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: microservice_implement_stockmanagement-sql-server-backend
  name: microservice_implement_stockmanagement-sql-server-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: microservice_implement_stockmanagement-sql-server-backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/task-manager-microservices-default: "true"
        io.kompose.service: microservice_implement_stockmanagement-sql-server-backend
    spec:
      containers:
        - image: microservice_implement_stockmanagement-sql-server-backend
          name: microservice_implement_stockmanagement-sql-server-backend
          ports:
            - containerPort: 1433
              hostPort: 1433
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}